<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"> <!-- name="structure" -->

<xacro:arg name="robot_name" default="bulldogbolt"/>


<!-- ********************************************************************** -->
<!-- ********************************************************************** -->
<!-- Car Body -->
<!-- ********************************************************************** -->
<!-- ********************************************************************** -->

<link name="base_link">
    <collision>
        <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>  
        <geometry>
            <box size="2.62 ${car_width} ${car_height}"/>
        </geometry>
    </collision>
    <visual>
        <!-- origin xyz="-0.25 0 ${base_height + 0.05}" rpy="0 0 0"/ -->  
        <origin xyz="0.05 0 0.3235" rpy="1.570796 0 1.570796"/>  
        <geometry>
            <!-- mesh filename="package://mir_vehicle/meshes/ford_escape_no_wheels_2.dae"/ -->
            <mesh filename="package://mir_vehicle_description/meshes/$(arg robot_name)/body.dae" scale="0.0383 0.0383 0.0383" />
        </geometry>
    </visual>
</link>

<joint name="inertial_joint" type="fixed">
    <parent link="base_link"/>
    <child link="main_mass"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
</joint>

<link name="main_mass" type="fixed">
    <parent link="inertial_joint"/>
    <inertial>
        <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
        <mass value="${base_mass}"/>
        <inertia
            ixx="${base_mass_ixx}"  ixy="0.000000" ixz="${base_mass_ixz}"
            iyy="${base_mass_iyy}" iyz="0.000000"
            izz="${base_mass_izz}"/>
    </inertial>
</link>


<!-- ********************************************************************** -->
<!-- ********************************************************************** -->
<!-- Wheels -->
<!-- ********************************************************************** -->
<!-- ********************************************************************** -->


<!-- ********************************************************************** -->
<!-- Back Left Wheel -->
<!-- ********************************************************************** -->

<joint name="back_left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="back_left_wheel_link"/>
    <origin xyz="${-tyre_x} ${tyre_y} 0.608" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.1"/>
    <limit effort="10000" velocity="100" />
    <joint_properties damping="0.0" friction="0.0" />
</joint>

<link name="back_left_wheel_link">
    <collision>
        <xacro:insert_block name="tyre_origin"/>
        <geometry>
            <cylinder length="${tyre_length}" radius="${tyre_radius}"/>
        </geometry>
    </collision>

    <visual>
        <origin xyz="-0.3065 -0.765 1.372" rpy="0 0 ${-PI/2}"/>
        <geometry>
            <mesh filename="package://mir_vehicle_description/meshes/$(arg robot_name)/wheel.dae" scale="0.0383 0.0383 0.0383"/>
        </geometry>
    </visual>

    <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${tyre_mass}"/>
        <inertia
            ixx="${tyre_mass_ixx}"  ixy="0.000000"  ixz="0.000000"
            iyy="${tyre_mass_iyy}"  iyz="0.000000"
            izz="${tyre_mass_izz}"/>
    </inertial>
</link>


<!-- ********************************************************************** -->
<!-- Back Right Wheel -->
<!-- ********************************************************************** -->

<joint name="back_right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="back_right_wheel_link"/>
    <origin xyz="${-tyre_x} ${-tyre_y} 0.608" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.1"/>
    <limit effort="10000" velocity="100" />
    <joint_properties damping="0.0" friction="0.0" />
</joint>

<link name="back_right_wheel_link">
    <collision>
        <xacro:insert_block name="tyre_origin"/>
        <geometry>
            <cylinder length="${tyre_length}" radius="${tyre_radius}"/>
        </geometry>
    </collision>

    <visual>
        <origin xyz="0.3065 0.765 1.372" rpy="0 0 ${PI/2}"/>
        <geometry>
            <mesh filename="package://mir_vehicle_description/meshes/$(arg robot_name)/wheel.dae" scale="0.0383 0.0383 0.0383"/>
        </geometry>
    </visual>

    <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${tyre_mass}"/>
        <inertia
            ixx="${tyre_mass_ixx}"  ixy="0.000000"  ixz="0.000000"
            iyy="${tyre_mass_iyy}"  iyz="0.000000"
            izz="${tyre_mass_izz}"/>
    </inertial>
</link>


<!-- ********************************************************************** -->
<!-- Front Left Wheel -->
<!-- ********************************************************************** -->

<joint name="front_left_wheel_joint" type="continuous">
    <parent link="front_left_steering_link"/>
    <child link="front_left_wheel_link"/>
    <origin xyz="0 ${str_length/2 + tyre_length/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>

    <dynamics damping="0.1"/>
    <limit effort="10000" velocity="100" />
    <joint_properties damping="0.0" friction="0.0" />
</joint>


<link name="front_left_wheel_link">
    <!-- ?? parent link="front_left_wheel_joint"/ -->
    <collision>     
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
             <cylinder length="${tyre_length}" radius="${tyre_radius}"/>
        </geometry>
    </collision>

    <visual>
        <origin xyz="-0.3065 -0.765 1.372" rpy="0 0 ${-PI/2}"/>
        <geometry>
            <mesh filename="package://mir_vehicle_description/meshes/$(arg robot_name)/wheel.dae" scale="0.0383 0.0383 0.0383"/>
        </geometry>
     </visual>

    <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${tyre_mass}"/>
        <inertia
            ixx="${tyre_mass_ixx}"  ixy="0.000000"  ixz="0.000000"
            iyy="${tyre_mass_iyy}"  iyz="0.000000"
            izz="${tyre_mass_izz}"/>
    </inertial>
</link>


<!-- ********************************************************************** -->
<!-- Front Right Wheel -->
<!-- ********************************************************************** -->

<joint name="front_right_wheel_joint" type="continuous">
    <parent link="front_right_steering_link"/>
    <child link="front_right_wheel_link"/>
    <origin xyz="0 ${-str_length/2 - tyre_length/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.1"/>
    <limit effort="10000" velocity="100" />
    <joint_properties damping="0.0" friction="0.0" />
</joint>

<link name="front_right_wheel_link">
    <collision>
        <xacro:insert_block name="tyre_origin"/>
        <geometry>
            <cylinder length="${tyre_length}" radius="${tyre_radius}"/>
        </geometry>
    </collision>

    <visual>
        <origin xyz="0.3065 0.765 1.372" rpy="0 0 ${PI/2}"/>
        <geometry>
            <mesh filename="package://mir_vehicle_description/meshes/$(arg robot_name)/wheel.dae" scale="0.0383 0.0383 0.0383"/>
        </geometry>  
    </visual>

    <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${tyre_mass}"/>
    <inertia
        ixx="${tyre_mass_ixx}"  ixy="0.000000"  ixz="0.000000"
        iyy="${tyre_mass_iyy}"  iyz="0.000000"
        izz="${tyre_mass_izz}"/>
    </inertial>
</link>


<!-- ********************************************************************** -->
<!-- Front Left Steering -->
<!-- ********************************************************************** -->

<joint name="front_left_steering_joint" type="revolute">
    <parent link="base_link"/>
    <child link="front_left_steering_link"/>
    <origin xyz="${tyre_x} ${car_width/2 + str_length/2} 0.608" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${-str_angle}" upper="${str_angle}" velocity="0.5"/>
</joint>

<link name="front_left_steering_link">
    <!-- ?? parent link="base_link"/ -->
    <collision>
        <xacro:insert_block name="tyre_origin"/>
        <geometry>
            <cylinder length="${str_length}" radius="${str_radius}"/>
        </geometry>
    </collision>

    <visual>
        <xacro:insert_block name="tyre_origin"/>
        <geometry>
            <cylinder length="${str_length}" radius="${str_radius}"/>
        </geometry>
    </visual>

    <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="10.00"/>
        <inertia
            ixx="0.4"  ixy="0.000000"  ixz="0.000000"
            iyy="0.6"  iyz="0.000000"
            izz="0.4"/>
    </inertial>
</link>


<!-- ********************************************************************** -->
<!-- Front Right Steering -->
<!-- ********************************************************************** -->

<joint name="front_right_steering_joint" type="revolute">
    <parent link="base_link"/>
    <child link="front_right_steering_link"/>
    <origin xyz="${tyre_x} ${-car_width/2 - str_length/2} 0.608" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${-str_angle}" upper="${str_angle}" velocity="0.5"/>
</joint>

<link name="front_right_steering_link">
    <collision>
        <xacro:insert_block name="tyre_origin"/>
        <geometry>
            <cylinder length="${str_length}" radius="${str_radius}"/>
        </geometry>
    </collision>

    <visual>
        <xacro:insert_block name="tyre_origin"/>
        <geometry>
            <cylinder length="${str_length}" radius="${str_radius}"/>
        </geometry>
    </visual>

    <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="10.00"/>
        <inertia
            ixx="0.4"  ixy="0.000000"  ixz="0.000000"
            iyy="0.6"  iyz="0.000000"
            izz="0.4"/>
    </inertial>
</link>


<!-- ********************************************************************** -->
<!-- ********************************************************************** -->
<!-- ********************************************************************** -->
<!-- ********************************************************************** -->

<!-- ********************************************************************** -->
<!-- motors and transmissions for the wheels -->
<!-- ********************************************************************** -->

<transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <!-- RWD -->
    <!--joint name="back_left_wheel_joint"-->
    <!-- FWD -->
    <joint name="front_left_wheel_joint">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
    </actuator>
</transmission>

<transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <!-- RWD -->
    <!--joint name="back_right_wheel_joint"-->
    <!-- FWD -->
    <joint name="front_right_wheel_joint">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
    </actuator>
</transmission>

<transmission name="rack_and_pinion_left">
    <type>transmission_interface/SimpleTransmission</type>
        <joint name="front_left_steering_joint">
        <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="eps_left">
        <hardwareInterface>PositionJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
    </actuator>
</transmission>

<transmission name="rack_and_pinion_right">
    <type>transmission_interface/SimpleTransmission</type>
        <joint name="front_right_steering_joint">
        <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="eps_right">
        <hardwareInterface>PositionJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
    </actuator>
</transmission>

</robot>
